## 1️⃣ Setup

### 1.1) Imports

In [1]:
import pandas as pd
import numpy as np


# Import for special characters (Mojibake)
from ftfy import fix_text

### 1.2) Get the data 📕

The data is available on Kagle, but on our case it was downloaded and saved inside **folder raw_data** as **winemag-data-130k-v2.csv**

In [2]:
# Data pulled into a Pandas DataFrame

df = pd.read_csv('../raw_data/winemag-data-130k-v2.csv')
df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

### 1.3) Have a look at the data 🔎

In [3]:
# Check the non-null count and data types for each column

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129971 entries, 0 to 129970
Data columns (total 14 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             129971 non-null  int64
 1   country                129908 non-null  object
 2   description            129971 non-null  object
 3   designation            92506 non-null   object
 4   points                 129971 non-null  int64
 5   price                  120975 non-null  float64
 6   province               129908 non-null  object
 7   region_1               108724 non-null  object
 8   region_2               50511 non-null   object
 9   taster_name            103727 non-null  object
 10  taster_twitter_handle  98758 non-null   object
 11  title                  129971 non-null  object
 12  variety                129970 non-null  object
 13  winery                 129971 non-null  object
dtypes: float64(1), int64(2), object(11)
memory usage: 13.9+ MB

## 2️⃣ Preprocessing

## 2.1) Check fully duplicated rows

In [4]:
# Fully duplicated rows (all columns identical)
full_dups = df[df.duplicated(keep=False)]

print("Fully duplicated rows:", full_dups.shape[0])
full_dups.head()

Fully duplicated rows: 0

Empty DataFrame
Columns: [Unnamed: 0, country, description, designation, points, price, province, region_1, region_2, taster_name, taster_twitter_handle, title, variety, winery]
Index: []

## 2.2) Rename first collumn as index

In [5]:
# Rename Unnamed: 0 collumn as index

df_clean = df.rename(columns={"Unnamed: 0": "index"})

df_clean.columns

Index(['index', 'country', 'description', 'designation', 'points', 'price',
       'province', 'region_1', 'region_2', 'taster_name',
       'taster_twitter_handle', 'title', 'variety', 'winery'],
      dtype='object')

## 2.3) Fix mojibake (accent corruption)

In [6]:
# All the columns with text data types will be converted to string and cleaned using the fix_text function from the ftfy library.
# This will help to correct any mojibake or encoding issues in the text data.
# When it converts to string the empty values will be converted to 'nan' string, so we will convert them to NaN after the fix_text function is applied.


# Create list with all Object columns (text columns) in the DataFrame
text_cols = [
    'country', 'description', 'designation', 'province',
    'region_1', 'region_2', 'taster_name', 'taster_twitter_handle',
    'title', 'variety', 'winery'
]

# convert all text columns to string and apply fix_text function
for col in text_cols:
    df_clean[col] = df_clean[col].astype(str).apply(fix_text)

# Convert 'nan' strings back to NaN
df_clean = df_clean.replace('nan', np.nan)

In [7]:
df_clean.sample(10)

,index,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
21144,21144,US,"This bottling is easy, light and crisp, starti...",NaN,87,13.0,California,Monterey,Central Coast,Matt Kettmann,@mattkettmann,Maddalena 2015 Pinot Grigio (Monterey),Pinot Grigio,Maddalena
124317,124317,Australia,Only a portion of this postage-stamp property ...,NaN,93,50.0,Victoria,Mornington Peninsula,NaN,Joe Czerwinski,@JoeCz,Eldridge Estate 2013 Pinot Noir (Mornington Pe...,Pinot Noir,Eldridge Estate
97004,97004,Italy,Here's a cheerful and approachable Montepulcia...,Jorio,87,14.0,Central Italy,Montepulciano d'Abruzzo,NaN,NaN,NaN,Umani Ronchi 2004 Jorio (Montepulciano d'Abru...,Montepulciano,Umani Ronchi
2146,2146,US,"This shows the tannic chewy, vegetal nature of...",NaN,84,28.0,Oregon,Rogue Valley,Southern Oregon,Paul Gregutt,@paulgwine,South Stage 2012 Carmenère (Rogue Valley),Carmenère,South Stage
65340,65340,US,"This is quite dry, as the label indicates, and...",Dry,88,6.0,Idaho,Idaho,NaN,Paul Gregutt,@paulgwine,Ste. Chapelle 2001 Dry Gewürztraminer (Idaho),Gewürztraminer,Ste. Chapelle
104809,104809,US,"This is 100% new oak (primarily Taransaud, 32 ...",Reserve,92,60.0,Washington,Yakima Valley,Columbia Valley,Paul Gregutt,@paulgwine,Sheridan Vineyard 2004 Reserve Cabernet Sauvig...,Cabernet Sauvignon,Sheridan Vineyard
12632,12632,Italy,This is a full and luminous white wine (made w...,Convento S.S. Annunciata,88,61.0,Lombardy,Terre di Franciacorta,NaN,NaN,NaN,Bellavista 2006 Convento S.S. Annunciata Chard...,Chardonnay,Bellavista
104562,104562,Israel,"Aromas of black cherry, lavender and thyme pro...",Just,90,25.0,Galilee,NaN,NaN,Mike DeSimone,@worldwineguys,Tulip Winery 2012 Just Cabernet Sauvignon (Gal...,Cabernet Sauvignon,Tulip Winery
12391,12391,US,"You'll find strong, bitter tannins, despite th...",Estate Pinchon Vineyard Spring Break,87,30.0,California,Santa Cruz Mountains,Central Coast,NaN,NaN,Burrell School Vineyards 2009 Estate Pinchon V...,Syrah,Burrell School Vineyards
109905,109905,Italy,"Blue flower, sunbaked earth, Mediterranean bru...",NaN,89,17.0,Sicily & Sardinia,Terre Siciliane,NaN,Kerin O'Keefe,@kerinokeefe,Colosi 2014 Nero d'Avola (Terre Siciliane),Nero d'Avola,Colosi

In [8]:
df_clean[df_clean['country'] == 'Portugal'].sample(10)

,index,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
97396,97396,Portugal,"Floral and fresh, this deliciously fragrant wi...",Conde de Vimioso Colheita Selectionada,87,9.0,Tejo,NaN,NaN,Roger Voss,@vossroger,Falua 2013 Conde de Vimioso Colheita Selection...,Portuguese White,Falua
17478,17478,Portugal,"Lightly wood aged, this pure Touriga Nacional ...",NaN,89,NaN,Dão,NaN,NaN,Roger Voss,@vossroger,Seacampo 2012 Touriga Nacional (Dão),Touriga Nacional,Seacampo
7215,7215,Portugal,The wine has a jammy character that gives it c...,Vintage,90,66.0,Port,NaN,NaN,Roger Voss,@vossroger,Quinta do Crasto 2015 Vintage (Port),Port,Quinta do Crasto
77908,77908,Portugal,This blend of the rare Caladoc with Tinta Rori...,Paxis,85,10.0,Lisboa,NaN,NaN,Roger Voss,@vossroger,DFJ Vinhos 2014 Paxis Red (Lisboa),Portuguese Red,DFJ Vinhos
31696,31696,Portugal,"A lean, cool, initially austere wine, well bal...",Reserva,88,28.0,Douro,NaN,NaN,Roger Voss,@vossroger,Poças 2007 Reserva Red (Douro),Portuguese Red,Poças
3903,3903,Portugal,Arinto is the real local grape of the small ci...,Prova Régia,87,11.0,Lisboa,NaN,NaN,Roger Voss,@vossroger,Quinta da Romeira 2014 Prova Régia Arinto (Lis...,Arinto,Quinta da Romeira
127987,127987,Portugal,"This is an attractively fruity, soft wine. Bal...",Monge Bruto,87,NaN,Tejo,NaN,NaN,Roger Voss,@vossroger,Quinta do Casal Branco 2012 Monge Bruto Sparkl...,Portuguese Sparkling,Quinta do Casal Branco
96472,96472,Portugal,Spicy wine from the wood and from the ripe ber...,Monte Altentejano Tinto,86,8.0,Alentejano,NaN,NaN,Roger Voss,@vossroger,DFJ Vinhos 2008 Monte Altentejano Tinto Red (A...,Portuguese Red,DFJ Vinhos
73964,73964,Portugal,"The wine is soft, creamy and ripe. It has whit...",NaN,85,15.0,Alentejano,NaN,NaN,Roger Voss,@vossroger,Dona Maria-Júlio Bastos 2016 White (Alentejano),Portuguese White,Dona Maria-Júlio Bastos
75873,75873,Portugal,"Full of red fruits and generous tannins, this ...",Quanta Terra Grande Reserva,88,25.0,Douro,NaN,NaN,Roger Voss,@vossroger,Caves Transmontanas 2012 Quanta Terra Grande R...,Portuguese Red,Caves Transmontanas

## 2.4 Handle missing values

In [9]:
# Check the % of missing values in each column, rounded by 2 decimal places.

(df_clean.isna().mean() * 100).round(2)

index                     0.00
country                   0.05
description               0.00
designation              28.83
points                    0.00
price                     6.92
province                  0.05
region_1                 16.35
region_2                 61.14
taster_name              20.19
taster_twitter_handle    24.02
title                     0.00
variety                   0.00
winery                    0.00
dtype: float64

# 2.4.1 - Price Column

In [10]:
# For Price the null values will be replace by 0
df_clean['price'] = df_clean['price'].fillna(0)

df_clean[df_clean["price"].isna()]

Empty DataFrame
Columns: [index, country, description, designation, points, price, province, region_1, region_2, taster_name, taster_twitter_handle, title, variety, winery]
Index: []

# 2.4.2 - Taster_name Column

In [11]:
# For taster_name the null values will be replace by 'unknown'
df_clean['taster_name'] = df_clean['taster_name'].fillna('unknown')

df_clean[df_clean["taster_name"].isna()]

Empty DataFrame
Columns: [index, country, description, designation, points, price, province, region_1, region_2, taster_name, taster_twitter_handle, title, variety, winery]
Index: []

# 2.4.3 - Country Column

In [ ]:
# For the country the null values will be replace according with the winery Location.
df_clean.loc[df_clean["winery"] == "Gotsa Family Wines", "country"] = "Georgia"
df_clean.loc[df_clean["winery"] == "Barton & Guestier", "country"] = "France"
df_clean.loc[df_clean["winery"] == "Kakhetia Traditional Winemaking", "country"] = "Georgia"
df_clean.loc[df_clean["winery"] == "Tsililis", "country"] = "Greece"
df_clean.loc[df_clean["winery"] == "Ross-idi", "country"] = "Bulgaria"
df_clean.loc[df_clean["winery"] == "Les Frères Dutruy", "country"] = "Switzerland"
df_clean.loc[df_clean["winery"] == "El Capricho", "country"] = "Spain"
df_clean.loc[df_clean["winery"] == "Büyülübağ", "country"] = "Turkey"
df_clean.loc[df_clean["winery"] == "Psagot", "country"] = "Israel"
df_clean.loc[df_clean["winery"] == "Orbelus", "country"] = "Bulgaria"
df_clean.loc[df_clean["winery"] == "St. Donat", "country"] = "Hungary"
df_clean.loc[df_clean["winery"] == "Familia Deicas", "country"] = "Uruguay"
df_clean.loc[df_clean["winery"] == "Bartho Eksteen", "country"] = "South Africa"
df_clean.loc[df_clean["winery"] == "Stone Castle", "country"] = "Kosovo"
df_clean.loc[df_clean["winery"] == "Teliani Valley", "country"] = "Georgia"
df_clean.loc[df_clean["winery"] == "Undurraga", "country"] = "Chile"
df_clean.loc[df_clean["winery"] == "Mt. Beautiful", "country"] = "New Zealand"
df_clean.loc[df_clean["winery"] == "Neumeister", "country"] = "Austria"
df_clean.loc[df_clean["winery"] == "Bachelder", "country"] = "Canada"
df_clean.loc[df_clean["winery"] == "Chilcas", "country"] = "Chile"
df_clean.loc[df_clean["winery"] == "Santa Ema", "country"] = "Chile"
df_clean.loc[df_clean["winery"] == "Newton Johnson", "country"] = "South Africa"
df_clean.loc[df_clean["winery"] == "Ktima Voyatzi", "country"] = "Greece"
df_clean.loc[df_clean["winery"] == "Lismore", "country"] = "South Africa"
df_clean.loc[df_clean["winery"] == "Logodaj", "country"] = "Bulgaria"
df_clean.loc[df_clean["winery"] == "Somlói Vándor", "country"] = "Hungary"
df_clean.loc[df_clean["winery"] == "Amiran Vepkhvadze", "country"] = "Georgia"

df_clean[df_clean["country"].isna()]

Empty DataFrame
Columns: [index, country, description, designation, points, price, province, region_1, region_2, taster_name, taster_twitter_handle, title, variety, winery]
Index: []

In [22]:
df_clean["country"].unique()

array(['Italy', 'Portugal', 'US', 'Spain', 'France', 'Germany',
       'Argentina', 'Chile', 'Australia', 'Austria', 'South Africa',
       'New Zealand', 'Israel', 'Hungary', 'Greece', 'Romania', 'Mexico',
       'Canada', 'Georgia', 'Turkey', 'Czech Republic', 'Slovenia',
       'Luxembourg', 'Croatia', 'Uruguay', 'England', 'Lebanon', 'Serbia',
       'Brazil', 'Moldova', 'Morocco', 'Peru', 'India', 'Bulgaria',
       'Cyprus', 'Armenia', 'Switzerland', 'Bosnia and Herzegovina',
       'Ukraine', 'Slovakia', 'Macedonia', 'Kosovo', 'China', 'Egypt'],
      dtype=object)

In [13]:
# Ckeck how many non.null per column
df_clean.info()


# Check the % of missing values in each column, rounded by 2 decimal places.
(df_clean.isna().mean() * 100).round(2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129971 entries, 0 to 129970
Data columns (total 14 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   index                  129971 non-null  int64
 1   country                129971 non-null  object
 2   description            129971 non-null  object
 3   designation            92506 non-null   object
 4   points                 129971 non-null  int64
 5   price                  129971 non-null  float64
 6   province               129908 non-null  object
 7   region_1               108724 non-null  object
 8   region_2               50511 non-null   object
 9   taster_name            129971 non-null  object
 10  taster_twitter_handle  98758 non-null   object
 11  title                  129971 non-null  object
 12  variety                129970 non-null  object
 13  winery                 129971 non-null  object
dtypes: float64(1), int64(2), object(11)
memory usage: 13.9+ MB

index                     0.00
country                   0.00
description               0.00
designation              28.83
points                    0.00
price                     0.00
province                  0.05
region_1                 16.35
region_2                 61.14
taster_name               0.00
taster_twitter_handle    24.02
title                     0.00
variety                   0.00
winery                    0.00
dtype: float64

In [18]:
df_clean[df_clean["province"].isna()]

,index,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
913,913,Georgia,"Amber in color, this wine has aromas of peach ...",Asureti Valley,87,30.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Gotsa Family Wines 2014 Asureti Valley Chinuri,Chinuri,Gotsa Family Wines
3131,3131,France,"Soft, fruity and juicy, this is a pleasant, si...",Partager,83,0.0,NaN,NaN,NaN,Roger Voss,@vossroger,Barton & Guestier NV Partager Red,Red Blend,Barton & Guestier
4243,4243,Georgia,"Violet-red in color, this semisweet wine has a...",Red Naturally Semi-Sweet,88,18.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Kakhetia Traditional Winemaking 2012 Red Natur...,Ojaleshi,Kakhetia Traditional Winemaking
9509,9509,Greece,This mouthwatering blend starts with a nose of...,Theopetra Malagouzia-Assyrtiko,92,28.0,NaN,NaN,NaN,Susan Kostrzewa,@suskostrzewa,Tsililis 2015 Theopetra Malagouzia-Assyrtiko W...,White Blend,Tsililis
9750,9750,Bulgaria,This orange-style wine has a cloudy yellow-gol...,Orange Nikolaevo Vineyard,89,28.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,Ross-idi 2015 Orange Nikolaevo Vineyard Chardo...,Chardonnay,Ross-idi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124176,124176,Switzerland,This Swiss red blend is composed of four varie...,Les Romaines,90,30.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,Les Frères Dutruy 2014 Les Romaines Red,Red Blend,Les Frères Dutruy
129407,129407,Spain,Dry spicy aromas of dusty plum and tomato add ...,Reserve,89,22.0,NaN,NaN,NaN,Michael Schachner,@wineschach,El Capricho 2015 Reserve Cabernet Sauvignon,Cabernet Sauvignon,El Capricho
129408,129408,Spain,El Capricho is one of Uruguay's more consisten...,Reserve,89,22.0,NaN,NaN,NaN,Michael Schachner,@wineschach,El Capricho 2015 Reserve Tempranillo,Tempranillo,El Capricho
129590,129590,Turkey,"A blend of 60% Syrah, 30% Cabernet Sauvignon a...",Shah,90,30.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Büyülübağ 2012 Shah Red,Red Blend,Büyülübağ
129900,129900,Israel,This wine offers a delightful bouquet of black...,NaN,91,32.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Psagot 2014 Merlot,Merlot,Psagot

In [27]:
df_clean[df_clean['winery'] == 'Familia Deicas']

,index,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
9133,9133,Uruguay,This mature Bordeaux-style blend is earthy on ...,Preludio Barrel Select Lote N 77,90,45.0,Juanico,NaN,NaN,Michael Schachner,@wineschach,Familia Deicas 2004 Preludio Barrel Select Lot...,Red Blend,Familia Deicas
10574,10574,Uruguay,"Grassy, leathery aromas lack ripeness and conc...",Deicas Mar de Piedras Vineyard,84,37.0,Uruguay,NaN,NaN,Michael Schachner,@wineschach,Familia Deicas 2015 Deicas Mar de Piedras Vine...,Tannat,Familia Deicas
14722,14722,Uruguay,Hard cherry and nail polish aromas rise up fro...,Don Pascual Reserve,82,12.0,Juanico,NaN,NaN,Michael Schachner,@wineschach,Familia Deicas 2008 Don Pascual Reserve Tannat...,Tannat,Familia Deicas
16000,16000,Uruguay,"Jumpy, jammy aromas of foxy black fruits are s...",Valle de los Manantiales Vineyard,86,40.0,NaN,NaN,NaN,Michael Schachner,@wineschach,Familia Deicas 2015 Valle de los Manantiales V...,Tannat,Familia Deicas
25485,25485,Uruguay,An opaque color is appropriate for this fully ...,Domaine Castelar Vineyard,89,40.0,Canelones,NaN,NaN,Michael Schachner,@wineschach,Familia Deicas 2015 Domaine Castelar Vineyard ...,Tannat,Familia Deicas
38811,38811,Uruguay,Ignore the crazy price on this aged Tannat and...,1st Cru d'Exception,88,120.0,Juanico,NaN,NaN,Michael Schachner,@wineschach,Familia Deicas 2006 1st Cru d'Exception Tannat...,Tannat,Familia Deicas
52550,52550,Uruguay,"Stewed black plum, brandied cherry, licorice a...",NaN,87,45.0,Juanico,NaN,NaN,Michael Schachner,@wineschach,Familia Deicas 2007 Tannat (Juanico),Tannat,Familia Deicas
56282,56282,Uruguay,Aromas of baked berries and spice are mature a...,Preludio,89,52.0,Juanico,NaN,NaN,Michael Schachner,@wineschach,Familia Deicas 2006 Preludio Red (Juanico),Red Blend,Familia Deicas
71451,71451,Uruguay,"Rusty in color, this maturing Tannat-led blend...",Preludio Barrel Select Lot N°92,87,60.0,Juanico,NaN,NaN,Michael Schachner,@wineschach,Familia Deicas 2009 Preludio Barrel Select Lot...,Red Blend,Familia Deicas
72049,72049,Uruguay,"Rusty in color, this maturing Tannat-led blend...",Preludio Barrel Select Lot N°92,87,60.0,Juanico,NaN,NaN,Michael Schachner,@wineschach,Familia Deicas 2009 Preludio Barrel Select Lot...,Red Blend,Familia Deicas
93548,93548,Uruguay,"Dense, cedary, rubbery aromas of blackberry an...",Massimo Deicas,90,130.0,Juanico,NaN,NaN,Michael Schachner,@wineschach,Familia Deicas 2008 Massimo Deicas Tannat (Jua...,Tannat,Familia Deicas
128749,128749,Uruguay,Dusty black-fruit aromas set up a palate that'...,Deicas,90,24.0,Uruguay,NaN,NaN,Michael Schachner,@wineschach,Familia Deicas 2015 Deicas Tannat (Uruguay),Tannat,Familia Deicas
129424,129424,Uruguay,An opaque color is appropriate for this fully ...,Domaine Castelar Vineyard,89,40.0,Canelones,NaN,NaN,Michael Schachner,@wineschach,Familia Deicas 2015 Domaine Castelar Vineyard ...,Tannat,Familia Deicas